# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-23 14:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PlanningPoker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ustory',
            name='game',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='game', to='PlanningPoker.Game'),
        ),
    ]
